INSERT INTO tb_category(name) VALUES ('Books');
INSERT INTO tb_category(name) VALUES ('Technology');
INSERT INTO tb_category(name) VALUES ('MOUSE GAMER');
INSERT INTO tb_category(name) VALUES ('Hardware');
INSERT INTO tb_category(name) VALUES ('Software');
INSERT INTO tb_category(name) VALUES ('Computação');
INSERT INTO tb_category(name) VALUES ('Telecomunicações');
INSERT INTO tb_category(name) VALUES ('Internet');
INSERT INTO tb_category(name) VALUES ('Eletrônica');
INSERT INTO tb_category(name) VALUES ('Robótica');
INSERT INTO tb_category(name) VALUES ('Inteligência artificial');
INSERT INTO tb_category(name) VALUES ('Placas de vídeo');
INSERT INTO tb_category(name) VALUES ('Placas-mãe');
INSERT INTO tb_category(name) VALUES ('Processadores');
INSERT INTO tb_category(name) VALUES ('Memória RAM');
INSERT INTO tb_category(name) VALUES ('Armazenamento');
INSERT INTO tb_category(name) VALUES ('Fontes de alimentação');
INSERT INTO tb_category(name) VALUES ('Gabinetes');
INSERT INTO tb_category(name) VALUES ('Monitores');
INSERT INTO tb_category(name) VALUES ('Teclado e mouse');
INSERT INTO tb_category(name) VALUES ('Headsets');
INSERT INTO tb_category(name) VALUES ('Webcams');
INSERT INTO tb_category(name) VALUES ('Joysticks');
INSERT INTO tb_category(name) VALUES ('Controles');
INSERT INTO tb_category(name) VALUES ('Jogos de videogame');
